#!/usr/bin/env php
<?php namespace Zae\WPVulnerabilities;

/**
 * @author       Ezra Pool <ezra@tsdme.nl>
 * @copyright (c), 2016 Ezra Pool
 */

(@include_once __DIR__ . '/../vendor/autoload.php') || @include_once __DIR__ . '/../../../autoload.php';

$app = new Scanner;

$app->resolve(Commands\ScanPluginsCommand::class);
$app->resolve(Commands\ScanThemesCommand::class);
$app->resolve(Commands\ScanWordpressCommand::class);

$app->run();